# Estágio de Build
FROM node:20-alpine AS builder

WORKDIR /app

# Copia tudo (usa .dockerignore)
COPY . .

# Instala as dependências (workspace root)
RUN npm install

# Roda o build do frontend (vai gerar na pasta raiz /app/dist/apps/web)
RUN npm run build --prefix apps/web

# Estágio de Produção (Nginx)
FROM nginx:alpine

# Remove o HTML padrão do Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos compilados do estágio anterior para o Nginx
COPY --from=builder /app/dist/apps/web /usr/share/nginx/html

# Copia a configuração customizada do Nginx (para React Router)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
